cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add/<int:product>/', AddProductToCartView.as_view(), name='add'),
    path('list/', ListCartView.as_view(), name='list'),
    path('delete/<int:pk>', DeleteItemDeleteView.as_view(), name="delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from reference.views import *
from products.views import *
from core.views import *
from profiles_app.views import UserHomeProfileAddressView
from admincoree.views import *
from django.conf import settings
from django.conf.urls.static import static
from search.views import *
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
import debug_toolbar
from rest_framework import routers
from reference.apiview import AuthorViewSet, SerieViewSet


router = routers.DefaultRouter()
router.register(r'api/author', AuthorViewSet)
router.register(r'api/serie', SerieViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-shop/products/',
         include('products.product_urls', namespace='products_book')),
    path('admin-shop/ref/', include('reference.author_urls',
                                    namespace='reference_author')),
    path('admin-shop/ref/', include('reference.series_urls',
                                    namespace='reference_series')),
    path('admin-shop/ref/', include('reference.publisher_urls',
                                    namespace='reference_publisher')),
    path('admin-shop/ref/', include('reference.genre_urls',
                                    namespace='reference_genre')),
    path('admin-shop/ref/', include('reference.manufacturer_urls',
                                    namespace='reference_manufacturer')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('about/', UserHomeAboutTemplateView.as_view(), name='about-store'),
    path('delivery/', UserHomeDeliveryTemplateView.as_view(), name='delivery-store'),
    path('profile/', UserHomeProfileTemplateView.as_view(), name='profile'),
    path('profile/address/<str:object>/', UserHomeProfileAddressView.as_view(), name='profile-address'),
    path('admin-shop/', StaffHomeTemplateView.as_view(), name='staff-page'),
    path('admin-shop/statistics/', Statistics.as_view(), name='staff-stats'),
    path('orders/', include('orders.urls', namespace="orders")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('search/', SearchView.as_view()),
    path('makesearch/', MakeSearchView.as_view(), name = "makesearch"),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html',
                                              redirect_authenticated_user=True, redirect_field_name=" "), name='login'),
    path('accounts/logout/',
         LogoutView.as_view(template_name='registration/logged_out.html')),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('change-password/done/', ChangePasswordDoneView.as_view(),
         name="password_change_done"),
    path('password-reset/', PasswordResetView.as_view(
        template_name='password/reset-password.html'), name="password-reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='password/reset-password-done.html'), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password/password-reset-confirm.html'), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password/password-reset-complete.html'), name='password_reset_complete'),
    path('', UserHomeTemplateView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

urlpatterns += router.urls

orders/urls.py
from django.urls import path

from .views import *

app_name = "orders"

urlpatterns = [
    path(
        'check-out',
        OrderCheckoutView.as_view(),
        name="check-out"),
    path(
        'success/<int:pk>/',
        OrderCheckoutSuccess.as_view(),
        name="success"),
    # path(
    #     'list/',
    #     views.OrdersList.as_view(),
    #     name="list")
    path(
        'list-admin/',
        OrdersListAdmin.as_view(),
        name="list-admin"),
    path('delete/<int:pk>', OrderDelete.as_view(), name="delete"),
    path('detail/<int:pk>', OrderDetailView.as_view(), name="detail"),
    path('update/<int:pk>', OrderUpdateView.as_view(), name="update")
]

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product

User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(User, related_name='Покупатель',
                             null=True, blank=True, on_delete=models.CASCADE)
    created_date = models.DateTimeField(
        verbose_name='Создано', auto_now=False, auto_now_add=True)
    updated_date = models.DateTimeField(
        verbose_name='Изменено', auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Корзина №{} для пользователя {}'.format(self.pk, self.user)
    
    @property
    def products_in_cart_count(self):
        total = 0
        for book in self.products.all():
            total += book.quantity
        return total

    @property
    def total_price(self):
        total = 0
        for book in self.products.all():
            total += book.price_total
        return total

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class ProductsInCart(models.Model):
    cart = models.ForeignKey(
        Cart, related_name='products', on_delete=models.CASCADE)
    book = models.ForeignKey(
        Product, on_delete=models.CASCADE)
    quantity = models.IntegerField('Количество', default=1)

    def __str__(self):
        return "Товар {name}, кол-во {quantity} в корзине".format(
            name=self.book.title,
            quantity=self.quantity)
    
    @property
    def price(self):
        return self.book.price

    @property
    def price_total(self):
        return self.book.price * self.quantity

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'
        unique_together = (
            ('cart', 'book'), 
        )

cart/forms.py
from django import forms
from .models import ProductsInCart

class AddToCartForm(forms.ModelForm):

    class Meta:
        model = ProductsInCart
        fields = [
            'book',
            'quantity'
        ]

        widgets = {
            'book': forms.HiddenInput(),
        }

cart/views.py
from django.shortcuts import render
from django.views.generic import *
from .forms import AddToCartForm
from .models import * 
from products.models import *
from orders.forms import CheckoutOrderForm
from reference.models import OrderStatus

new_order_status = OrderStatus.objects.get(pk=1)

class AddProductToCartView(UpdateView):
    template_name = "cart/add-to-cart.html"
    form_class = AddToCartForm
    model = ProductsInCart

    def get_object(self):
        cart_id = self.request.session.get('cart_id')
        book_id = self.kwargs.get('product')  
        usr = None
        if self.request.user.is_authenticated:
            usr = self.request.user
        cart, cart_created = Cart.objects.get_or_create(
            pk = cart_id,
            defaults = {
                'user': usr,
            }
        )
        if cart_created:
            self.request.session['cart_id'] = cart.pk
        book_id = self.kwargs.get('product')  
        book = Product.objects.get(pk=book_id)
        obj, created = self.model.objects.get_or_create(
            cart = cart,
            book = book,
            defaults = {
                'cart': cart,
                'book': book,
                'quantity': 0
            }
        ) 
        return obj
    
    def get_success_url(self):
        return self.request.POST.get('next', '/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = self.request.GET.get('next', '/')
        return context

class ListCartView(DetailView):
    template_name = "cart/list-cart.html"
    model = Cart
    
    def get_object(self):
        cart_id = self.request.session.get('cart_id')
        cart, cart_created = Cart.objects.get_or_create(
            pk = cart_id,
            defaults = {
                'user': self.request.user,
            }
        )
        return cart 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        checkout_form = CheckoutOrderForm()
        checkout_form.fields['cart'].initial = self.object
        checkout_form.fields['status'].initial = new_order_status
        context["form"] = checkout_form
        return context
    
class DeleteItemDeleteView(DeleteView):
    model = ProductsInCart
    template_name = 'cart/delete-item.html'

    def get_success_url(self):
        return self.request.POST.get('next', '/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = self.request.GET.get('next', '/')
        return context

cart/templates/cart/add-to-cart.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

{% block body %}
    <div class="container">
        <h1>{{ object.book.name }}</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="hidden" name="next" value="{{next}}">
            <button type="submit" class="btn btn-primary btn-lg btn-block" href="">Добавить в корзину</button>
        </form>
    </div>
{% endblock body %}

cart/templates/cart/delete-item.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container">


<h1>{{ object.book.title }}</h1>
<h2>{{ object.quantity }} шт</h2>

<form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-block">Удалить?</button>
</form>
</div>
{% endblock body %}

cart/templates/cart/list-cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


{% block body %}
<div class="container">
<h1>Корзина</h1>
    <table class="table table-striped">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Книга</th>
        <th scope="col">Кол-во</th>
        <th scope="col">Цена за шт.</th>
        <th scope="col">Цена всего</th>
        <th scope="col">..</th>
        </tr>
    </thead>
    <tbody>
{% for product in object.products.all %}
        <tr>
        <th scope="row">{{ product.pk }}</th>
        <td>{{ product.book.title }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.price_total }}</td>
        <td>
            <a href="{% url 'cart:delete' product.pk %}?next=/cart/list/" class="btn btn-danger btn-small"><i class="fas fa-trash"></i></a>
            <a href="{% url 'cart:add' product.book.pk %}?next=/cart/list/" class="btn btn-success btn-small"><i class="fas fa-edit"></i></a>
        </td>
        </tr>
{% endfor %}
        <tr>
            <th scope="row" colspan="2">Итого:</th>
            <th scope="row" colspan="2">{{ object.products_in_cart_count }} шт.</th>
            <th scope="row" colspan="2">{{ object.total_price }} BYN</th>
        </tr>
    </tbody>
    </table>
    {% if object.products_in_cart_count > 0 %}
        <div class="card bg-light border-primary mb-3">
            <h5 class="card-header border-primary">Оформить заказ</h5>
                <form action="{% url 'orders:check-out' %}" method="POST" class="card-body">
                    {% csrf_token %}
                    <h5 class="card-title">* - обязательны для заполнения</h5>
                    <p class="card-text">{{ form|crispy }}</p>
                    <button class="btn btn-danger btn-block" type="submit">Оформить заказ</button>
                </form>
        </div>
    {% endif %}
{% endblock body %}

cart/templates/cart/view-cart.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container">
<h1>Корзина</h1>
    <table class="table table-striped">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Книга</th>
        <th scope="col">Кол-во</th>
        <th scope="col">Цена за шт.</th>
        <th scope="col">Цена всего</th>
        <th scope="col">..</th>
        </tr>
    </thead>
    <tbody>
{% for product in object.products.all %}
        <tr>
        <th scope="row">{{ product.pk }}</th>
        <td>{{ product.book.title }}</td>
        <td>{{ product.quantity }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.price_total }}</td>
        <td>
            <a href="{% url 'cart:delete' product.pk %}?next=/cart/view/" class="btn btn-danger btn-small"><i class="fas fa-trash"></i></a>
            <a href="{% url 'cart:add-product-to-cart' product.product.pk %}?next=/cart/view/" class="btn btn-success btn-small"><i class="fas fa-edit"></i></a>
        </td>
        </tr>
{% endfor %}
        <tr>
            <th scope="row" colspan="2">Итого:</th>
            <th scope="row" colspan="2">{{ object.products_in_cart_count }} шт.</th>
            <th scope="row" colspan="2">{{ object.total_price }} BYN</th>
        </tr>
    </tbody>
    </table>
    {% if object.products_in_cart_count > 0 %}
        <div class="card bg-light border-primary mb-3">
            <h5 class="card-header border-primary">Оформить заказ</h5>
                <form action="{% url 'orders:check-out' %}" method="POST" class="card-body">
                    {% csrf_token %}
                    <h5 class="card-title">* - обязательны для заполнения</h5>
                    <p class="card-text">{{ form|crispy }}</p>
                    <button class="btn btn-danger btn-block" type="submit">Оформить заказ</button>
                </form>
        </div>
    {% endif %}
{% endblock body %}