cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add/<int:product>/', AddProductToCartView.as_view(), name='add'),
    path('list/', ListCartView.as_view(), name='list'),
    path('delete/<int:pk>', DeleteItemDeleteView.as_view(), name="delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from reference.views import *
from products.views import *
from core.views import *
from profiles_app.views import UserHomeProfileAddressView
from admincoree.views import *
from django.conf import settings
from django.conf.urls.static import static
from search.views import *
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
import debug_toolbar
from rest_framework import routers
from reference.apiview import AuthorViewSet, SerieViewSet


router = routers.DefaultRouter()
router.register(r'api/author', AuthorViewSet)
router.register(r'api/serie', SerieViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-shop/products/',
         include('products.product_urls', namespace='products_book')),
    path('admin-shop/ref/', include('reference.author_urls',
                                    namespace='reference_author')),
    path('admin-shop/ref/', include('reference.series_urls',
                                    namespace='reference_series')),
    path('admin-shop/ref/', include('reference.publisher_urls',
                                    namespace='reference_publisher')),
    path('admin-shop/ref/', include('reference.genre_urls',
                                    namespace='reference_genre')),
    path('admin-shop/ref/', include('reference.manufacturer_urls',
                                    namespace='reference_manufacturer')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('about/', UserHomeAboutTemplateView.as_view(), name='about-store'),
    path('delivery/', UserHomeDeliveryTemplateView.as_view(), name='delivery-store'),
    path('profile/', UserHomeProfileTemplateView.as_view(), name='profile'),
    path('profile/address/<str:object>/', UserHomeProfileAddressView.as_view(), name='profile-address'),
    path('admin-shop/', StaffHomeTemplateView.as_view(), name='staff-page'),
    path('admin-shop/statistics/', Statistics.as_view(), name='staff-stats'),
    path('orders/', include('orders.urls', namespace="orders")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('search/', SearchView.as_view()),
    path('makesearch/', MakeSearchView.as_view(), name = "makesearch"),
    path('accounts/login/', LoginView.as_view(template_name='registration/login.html',
                                              redirect_authenticated_user=True, redirect_field_name=" "), name='login'),
    path('accounts/logout/',
         LogoutView.as_view(template_name='registration/logged_out.html')),
    path('change-password/', ChangePasswordView.as_view(), name="change-password"),
    path('change-password/done/', ChangePasswordDoneView.as_view(),
         name="password_change_done"),
    path('password-reset/', PasswordResetView.as_view(
        template_name='password/reset-password.html'), name="password-reset"),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='password/reset-password-done.html'), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password/password-reset-confirm.html'), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password/password-reset-complete.html'), name='password_reset_complete'),
    path('', UserHomeTemplateView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

urlpatterns += router.urls

orders/urls.py
from django.urls import path

from .views import *

app_name = "orders"

urlpatterns = [
    path(
        'check-out',
        OrderCheckoutView.as_view(),
        name="check-out"),
    path(
        'success/<int:pk>/',
        OrderCheckoutSuccess.as_view(),
        name="success"),
    # path(
    #     'list/',
    #     views.OrdersList.as_view(),
    #     name="list")
    path(
        'list-admin/',
        OrdersListAdmin.as_view(),
        name="list-admin"),
    path('delete/<int:pk>', OrderDelete.as_view(), name="delete"),
    path('detail/<int:pk>', OrderDetailView.as_view(), name="detail"),
    path('update/<int:pk>', OrderUpdateView.as_view(), name="update")
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from cart.models import Cart
from reference.models import OrderStatus


class Order(models.Model):
    cart = models.ForeignKey(
        Cart,
        verbose_name="Корзина",
        on_delete=models.PROTECT)
    status = models.ForeignKey(
        "reference.OrderStatus",
        verbose_name="Статус заказа",
        on_delete=models.PROTECT)
    phone = models.CharField(
        verbose_name="Контактный телефон",
        help_text="+37529-123-45-67",
        max_length=16)
    email = models.EmailField(
        verbose_name="Электронная почта",
        null=True,
        blank=True,
        help_text="user@mail.com")
    delivery_address = models.TextField(
        "Адрес доставки",
        null=True,
        blank=True,
        help_text="Минск, ул. Ленина, 3-12"
        )
    comments = models.TextField(
        "Дополнительная информация",
        null=True,
        blank=True
        )
    created_date = models.DateTimeField(
        "Дата создания",
        auto_now=False,
        auto_now_add=True)
    updated_date = models.DateTimeField(
        "Дата изменения",
        auto_now=True,
        auto_now_add=False)

    def __str__(self):
        return "Заказ № {}, от {}".format(
            self.pk,
            self.created_date.strftime('%d.%m.%Y'))

orders/forms.py
from django import forms

from .models import Order


class CheckoutOrderForm(forms.ModelForm):
    class Meta:
        model = Order

        fields = [
            'cart',
            'status',
            'phone',
            'email',
            'delivery_address',
            'comments',
        ]
        widgets = {
            'cart': forms.HiddenInput(),
            'status': forms.HiddenInput(),
        }

orders/views.py
from django.views.generic import (
    UpdateView, DetailView, ListView,
    DeleteView, CreateView)
from django.urls import reverse_lazy

from .forms import CheckoutOrderForm
from .models import Order, OrderStatus
from django.shortcuts import get_object_or_404


class OrderCheckoutView(CreateView):
    model = Order
    template_name = 'cart/list-cart.html'
    form_class = CheckoutOrderForm

    def get_success_url(self):
        del self.request.session['cart_id']
        return reverse_lazy('orders:success', kwargs={'pk': self.object.pk})


class OrderCheckoutSuccess(DetailView):
    model = Order
    template_name = 'orders/success.html'


class OrdersListAdmin(ListView):
    model = Order
    template_name = 'orders/list-admin.html'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active"] = "orders"
        context["total"] = self.object_list.count()
        return context


class OrderDelete(DeleteView):
    model = Order
    template_name = 'orders/delete-order.html'

    def get_success_url(self):
        return self.request.POST.get('next', '/orders/list-admin')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = self.request.GET.get('next', '/')
        return context


class OrderDetailView(DetailView):
    template_name = 'orders/detail-order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        Order.objects.filter(pk=self.kwargs.get('pk'), status="1").update(status="2")
        return context

    # способ 2 ч\з get_object
    # def get_object(self, *args, **kwargs):
    #     obj = super().get_object(*args, **kwargs)
    #     obj.status = OrderStatus.objects.get(pk=2)
    #     obj.save()
    #     return obj


class OrderUpdateView(UpdateView):
    model = Order
    template_name = 'orders/update-order.html'
    fields = ['cart',
              'status',
              'phone',
              'email',
              'delivery_address',
              'comments',
              ]

    def get_success_url(self):
        return self.request.POST.get('next', '/orders/list-admin')

orders/templates/orders/delete-order.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="container">


<h1>Удалить заказ № {{  object.pk  }}</h1>

<form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-block">Удалить?</button>
</form>
</div>
{% endblock body %}

orders/templates/orders/detail-order.html
{% extends 'admin-base.html'%}
{% load static %}
{% block title %}
             Отображение заказа № {{ object.pk }}
{%endblock title %}
{% block body %}
<div class="container">
<br>
    <div class="card-body">
            <h5 class="card-title">{{ object }}</h5>
            <p class="card-text">{{ object.cart }}</p>
            <p class="card-text">Статус заказа: {{ object.status }}</p>
            <a href="{% url 'orders:list-admin' %}" class="btn btn-primary">Назад к заказам</a>
    </div>
</div>
{% endblock body %} 

orders/templates/orders/list-admin.html
{% extends 'admin-base.html'%}
{% load static %}
{% block body %}
<div class="container">
    <h6>Заказов всего: {{ total }} шт.</h6>
    <h1>Список заказов</h1>
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Заказ</th>
            <th scope="col">Статус</th>
            <th scope="col">Клиент</th>
            <th scope="col">Телефон</th>
            <th scope="col">email</th>
            <th scope="col">..</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ object.pk }}</th>
                        <td>{{ object }}</td>
                        <td>{{ object.status.name }}</td>
                        <td>{{ object.cart.user.username }}</td>
                        <td>{{ object.phone }}</td>
                        <td>{{ object.email }}</td>
                        <td>
                            <a href="{% url 'orders:delete' object.pk %}" class="btn btn-danger btn-small mx-1"><i class="fas fa-trash"></i>
                            <a href="{% url 'orders:detail' object.pk %}" class="btn btn-info btn-small mx-1"><i class="fas fa-clipboard-list"></i>
                            <a href="{% url 'orders:update' object.pk %}" class="btn btn-success btn-small mx-1"><i class="fas fa-edit"></i>
                        </td>
                    </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "paginator.html" %}
</div>
{% endblock %}

orders/templates/orders/success.html
{% extends 'base.html'%}
{% load static %}
{% block body %}
<div class="container">
    <h1>{{ object }} успешно оформлен!</h1>
    <p>В ближайшее время с Вами свяжется нам менеджер для уточнения деталей!</p>
    <h2>Спасибо, что выбрали наш магазин!</h2>

</div>
{% endblock %}

orders/templates/orders/update-order.html
{% extends 'admin-base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">


{% block head %}
{% endblock head %}

{% block title %}
Редактирование заказа
{% endblock title %}



{% block body %}
<div class="container">
    {% block background_style %}
    {% endblock background_style %}
    <h2 align="center">Редактирование заказа</h2>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form |crispy }}
        </div>
        </enctype>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Отправить</button>
</div>
{% endblock body %}

</form>